// ============================================
// @qalcuity/analytics — Metric Definitions Registry
// Single source of truth for all analytics metrics
// ============================================

import type { MetricDefinition, MetricCategory } from './types';

/**
 * Registry of all built-in metric definitions.
 * Each metric defines its formula, source, category, and supported dimensions.
 */
export const METRIC_DEFINITIONS: MetricDefinition[] = [
    // === FINANCE METRICS ===
    {
        id: 'revenue',
        name: 'Revenue',
        nameKey: 'metrics.revenue',
        description: 'Total recognized sales revenue from approved and posted invoices minus returns',
        category: 'finance',
        format: 'currency',
        formula: 'SUM(invoice.total) WHERE invoice.status IN (PAID, SENT)',
        source: 'Sales Invoice',
        dataType: 'Decimal(15,2)',
        aggregationType: 'sum',
        dimensions: ['date', 'branch', 'customer', 'product', 'category'],
        measures: ['invoice_total'],
        isDefault: true,
    },
    {
        id: 'total_expenses',
        name: 'Total Expenses',
        nameKey: 'metrics.total_expenses',
        description: 'Total business expenses from approved payments',
        category: 'finance',
        format: 'currency',
        formula: 'SUM(payment.amount) WHERE payment.type = EXPENSE AND payment.status = COMPLETED',
        source: 'Payment Records',
        dataType: 'Decimal(15,2)',
        aggregationType: 'sum',
        dimensions: ['date', 'branch', 'category'],
        measures: ['payment_amount'],
        isDefault: true,
    },
    {
        id: 'gross_profit',
        name: 'Gross Profit',
        nameKey: 'metrics.gross_profit',
        description: 'Revenue minus Cost of Goods Sold',
        category: 'finance',
        format: 'currency',
        formula: 'Revenue - COGS',
        source: 'Calculated',
        dataType: 'Decimal(15,2)',
        aggregationType: 'sum',
        dimensions: ['date', 'branch', 'product'],
        measures: ['revenue', 'cogs'],
        isDefault: true,
    },
    {
        id: 'net_income',
        name: 'Net Income',
        nameKey: 'metrics.net_income',
        description: 'Total revenue minus total expenses',
        category: 'finance',
        format: 'currency',
        formula: 'Revenue - Total Expenses',
        source: 'Calculated',
        dataType: 'Decimal(15,2)',
        aggregationType: 'sum',
        dimensions: ['date', 'branch'],
        measures: ['revenue', 'expenses'],
        isDefault: true,
    },
    {
        id: 'cash_flow',
        name: 'Net Cash Flow',
        nameKey: 'metrics.cash_flow',
        description: 'Total income minus total expenses for the period',
        category: 'finance',
        format: 'currency',
        formula: 'SUM(income) - SUM(expenses)',
        source: 'Payment Records',
        dataType: 'Decimal(15,2)',
        aggregationType: 'sum',
        dimensions: ['date', 'branch'],
        measures: ['income', 'expenses'],
        isDefault: true,
    },
    {
        id: 'ar_aging',
        name: 'Accounts Receivable Aging',
        nameKey: 'metrics.ar_aging',
        description: 'Outstanding receivables categorized by age',
        category: 'finance',
        format: 'currency',
        formula: 'SUM(invoice.total) WHERE invoice.status IN (SENT, OVERDUE)',
        source: 'Sales Invoice',
        dataType: 'Decimal(15,2)',
        aggregationType: 'sum',
        dimensions: ['date', 'customer', 'branch', 'aging_bucket'],
        measures: ['outstanding_amount'],
        isDefault: true,
    },

    // === SALES METRICS ===
    {
        id: 'total_deals',
        name: 'Total Deals',
        nameKey: 'metrics.total_deals',
        description: 'Total number of deals in the pipeline',
        category: 'sales',
        format: 'count',
        formula: 'COUNT(deal)',
        source: 'Deal',
        dataType: 'integer',
        aggregationType: 'count',
        dimensions: ['date', 'stage', 'salesperson', 'branch'],
        measures: ['deal_count'],
        isDefault: true,
    },
    {
        id: 'win_rate',
        name: 'Win Rate',
        nameKey: 'metrics.win_rate',
        description: 'Percentage of deals won vs total qualified deals',
        category: 'sales',
        format: 'percentage',
        formula: 'COUNT(deal WHERE stage = CLOSED_WON) / COUNT(deal WHERE stage NOT IN (DISCOVERY, QUALIFICATION))',
        source: 'Deal',
        dataType: 'decimal',
        aggregationType: 'count',
        dimensions: ['date', 'salesperson', 'branch', 'product'],
        measures: ['won_deals', 'total_deals'],
        isDefault: true,
    },
    {
        id: 'pipeline_value',
        name: 'Pipeline Value',
        nameKey: 'metrics.pipeline_value',
        description: 'Total value of all active deals in the pipeline',
        category: 'sales',
        format: 'currency',
        formula: 'SUM(deal.value) WHERE deal.stage NOT IN (CLOSED_WON, CLOSED_LOST)',
        source: 'Deal',
        dataType: 'Decimal(15,2)',
        aggregationType: 'sum',
        dimensions: ['date', 'stage', 'salesperson', 'branch'],
        measures: ['deal_value'],
        isDefault: true,
    },
    {
        id: 'avg_deal_size',
        name: 'Average Deal Size',
        nameKey: 'metrics.avg_deal_size',
        description: 'Average value of closed won deals',
        category: 'sales',
        format: 'currency',
        formula: 'AVG(deal.value) WHERE deal.stage = CLOSED_WON',
        source: 'Deal',
        dataType: 'Decimal(15,2)',
        aggregationType: 'avg',
        dimensions: ['date', 'salesperson', 'branch', 'product'],
        measures: ['deal_value'],
        isDefault: true,
    },
    {
        id: 'lead_conversion_rate',
        name: 'Lead Conversion Rate',
        nameKey: 'metrics.lead_conversion_rate',
        description: 'Percentage of leads that convert to deals',
        category: 'crm',
        format: 'percentage',
        formula: 'COUNT(deal) / COUNT(lead) * 100',
        source: 'Lead + Deal',
        dataType: 'decimal',
        aggregationType: 'count',
        dimensions: ['date', 'source', 'salesperson'],
        measures: ['lead_count', 'deal_count'],
        isDefault: true,
    },

    // === INVENTORY METRICS ===
    {
        id: 'total_stock_value',
        name: 'Total Stock Value',
        nameKey: 'metrics.total_stock_value',
        description: 'Total value of current inventory',
        category: 'inventory',
        format: 'currency',
        formula: 'SUM(product.price * product.stock)',
        source: 'Product',
        dataType: 'Decimal(15,2)',
        aggregationType: 'sum',
        dimensions: ['category', 'branch', 'supplier'],
        measures: ['stock_value'],
        isDefault: true,
    },
    {
        id: 'stock_turnover',
        name: 'Stock Turnover Rate',
        nameKey: 'metrics.stock_turnover',
        description: 'How many times inventory is sold and replaced in a period',
        category: 'inventory',
        format: 'number',
        formula: 'COGS / Average Inventory',
        source: 'Calculated',
        dataType: 'decimal',
        aggregationType: 'avg',
        dimensions: ['date', 'category', 'product'],
        measures: ['cogs', 'avg_inventory'],
        isDefault: true,
    },
    {
        id: 'low_stock_count',
        name: 'Low Stock Items',
        nameKey: 'metrics.low_stock_count',
        description: 'Number of products below minimum stock level',
        category: 'inventory',
        format: 'count',
        formula: 'COUNT(product WHERE product.stock < product.minStock)',
        source: 'Product',
        dataType: 'integer',
        aggregationType: 'count',
        dimensions: ['category', 'branch', 'supplier'],
        measures: ['product_count'],
        isDefault: true,
    },

    // === HR METRICS ===
    {
        id: 'headcount',
        name: 'Headcount',
        nameKey: 'metrics.headcount',
        description: 'Total number of active employees',
        category: 'hr',
        format: 'count',
        formula: 'COUNT(employee WHERE status = ACTIVE)',
        source: 'Employee',
        dataType: 'integer',
        aggregationType: 'count',
        dimensions: ['department', 'branch', 'position'],
        measures: ['employee_count'],
        isDefault: true,
    },
    {
        id: 'attendance_rate',
        name: 'Attendance Rate',
        nameKey: 'metrics.attendance_rate',
        description: 'Percentage of present days vs working days',
        category: 'hr',
        format: 'percentage',
        formula: 'COUNT(attendance WHERE status = PRESENT) / COUNT(attendance) * 100',
        source: 'Attendance Record',
        dataType: 'decimal',
        aggregationType: 'count',
        dimensions: ['date', 'department', 'employee'],
        measures: ['present_count', 'total_count'],
        isDefault: true,
    },
    {
        id: 'total_payroll',
        name: 'Total Payroll',
        nameKey: 'metrics.total_payroll',
        description: 'Total payroll cost for the period',
        category: 'hr',
        format: 'currency',
        formula: 'SUM(payroll.netSalary) WHERE status = PAID',
        source: 'Payroll Record',
        dataType: 'Decimal(15,2)',
        aggregationType: 'sum',
        dimensions: ['date', 'department', 'branch'],
        measures: ['net_salary'],
        isDefault: true,
    },
    {
        id: 'turnover_rate',
        name: 'Employee Turnover Rate',
        nameKey: 'metrics.turnover_rate',
        description: 'Percentage of employees who left vs total headcount',
        category: 'hr',
        format: 'percentage',
        formula: 'COUNT(employee WHERE status = TERMINATED) / COUNT(employee) * 100',
        source: 'Employee',
        dataType: 'decimal',
        aggregationType: 'count',
        dimensions: ['date', 'department', 'branch'],
        measures: ['terminated_count', 'total_count'],
        isDefault: true,
    },
];

/**
 * Get a metric definition by ID.
 */
export function getMetricById(id: string): MetricDefinition | undefined {
    return METRIC_DEFINITIONS.find(m => m.id === id);
}

/**
 * Get all metric definitions for a given category.
 */
export function getMetricsByCategory(category: MetricCategory): MetricDefinition[] {
    return METRIC_DEFINITIONS.filter(m => m.category === category);
}

/**
 * Get all default (built-in) metric definitions.
 */
export function getDefaultMetrics(): MetricDefinition[] {
    return METRIC_DEFINITIONS.filter(m => m.isDefault);
}
